# en: False
en: True
name: ZO_Estim_MC
sigma: 0.01
n_sample: 1
signSGD: False

actv_perturb_layer_list: null
# actv_perturb_layer_list: ['Adapter',]
# actv_perturb_block_idx_list: all
# actv_perturb_block_idx_list: [8,]

# param_perturb_param_list: null
param_perturb_param_list: ['adapter_down.weight','adapter_up.weight']
param_perturb_block_idx_list: all
# param_perturb_param_list: ['adapter_up.weight']
# param_perturb_block_idx_list: [8,]

# obj_fn_type: classifier
obj_fn_type: classifier_layerwise

quantized: False

# estimate_method: forward
estimate_method: antithetic

# sample_method: uniform
sample_method: gaussian
# sample_method: bernoulli
# sample_method: coord_basis

normalize_perturbation: True