en: True
name: ZO_Estim_MC
sigma: 0.01
n_sample: 10
signSGD: False

param_perturb_list: null
actv_perturb_list: ['adapter_mlp',]

quantize_method: None

mask_method: None
# mask_method: block-10
# mask_method: layer

estimate_method: forward
# estimate_method: antithetic

# obj_fn_type: classifier
# perturb_method: batch

obj_fn_type: classifier_layerwise
perturb_method: activation

# sample_method: uniform
# sample_method: gaussian
# sample_method: bernoulli
sample_method: coord_basis
